Repository part2-11team/rolling-paper, pull requests merged in 2024-03, with the labels that each got.

#26 [feat/#25] 롤링페이퍼 서버에서 가져오기
  src/pages/PaperListPage/PaperListPage.js
Labels: ✨feat, ✅ mod

#28 [feat/#13] 간단한 기능들 구현
  src/pages/PostPage/PostPage.js
  src/pages/PostPage/PostPage.style.js
Labels: ✨feat

#32 [feat/#29] POST page - Background Images
  src/pages/PostPage/PostPage.js
  src/pages/PostPage/PostPage.style.js
Labels: ✨feat

#42 [UI/#41] : 롤링 페이퍼 리스트 스켈레톤 ui 적용
  src/components/Skeleton/DelayComponent.js
  src/components/Skeleton/PaperListSkeleton/PaperListSkeleton.jsx
  src/components/Skeleton/PaperListSkeleton/PaperListSkeleton.style.js
  src/components/Skeleton/PaperListSkeleton/index.js
  src/pages/PaperListPage/PaperListPage.js
Labels: ✨feat, 💄ui

#43 [Feat/#34] 생성하기 버튼 기능 구현
  src/pages/PostPage/PostPage.js
Labels: ✨feat

#55 [FIX/#54] list 페이지 헤더 추가 및 warning 해결
  src/pages/MainPage/MainPage.jsx
  src/pages/MainPage/MainPage.style.js
  src/pages/PaperListPage/PaperListPage.js
Labels: ➕add, 🔨 fix

#63 [Feat/#62] 생성하기 버튼 기능 구현
  .DS_Store
  .gitignore
  src/.DS_Store
  src/App.js
  src/assets/.DS_Store
  src/assets/icon/.DS_Store
  src/assets/images/background-img1.jpeg
  src/assets/images/background-img2.jpeg
  src/assets/images/background-img3.jpeg
  src/assets/images/background-img4.jpeg
  src/components/PostImageButton/PostImageButton.js
  src/components/PostImageButton/PostImageButton.style.js
  src/pages/PostPage/PostPage.js
  src/pages/PostPage/PostPage.style.js
  src/pages/PostPage/index.js
Labels: ✨feat

#89 [Feat/#88] 에러페이지 구현
  src/API.js
  src/App.js
  src/assets/icon/error-icon.png
  src/pages/ErrorPage/ErrorPage.jsx
  src/pages/ErrorPage/ErrorPage.style.js
  src/pages/PostPage/PostPage.jsx
  src/pages/PostPage/PostPage.style.js
  src/style/font.css
Labels: ✨feat

#97 [ MOD ] 에러페이지 props 변경
  src/API.js
  src/pages/ErrorPage/ErrorPage.jsx
  src/pages/ErrorPage/ErrorPage.style.js
  src/pages/PostPage/PostPage.jsx
Labels: ✅ mod
